name: Labeler

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  labeler:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@de749cf181958193cb7debf1a9c5bb28922f3e1b # ratchet:crazy-max/ghaction-github-labeler@v5.0.0
        with:
          skip-delete: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
